version: "3.7"
services:
  service-registry:
    image: "sf_service-registry-microservice"
    container_name: registry
    ports:
      - 8761:8761
    depends_on:
      - mongodb
    networks:
      - network-eureka
  cloud-gatway:
    image: "sf_cloud-microservice"
    ports:
      - 9191:9191
    depends_on:
      - nfts-microservice
      - ServiceRegistry-Microservice


    networks:
      - network-eureka   
    environment:
      eureka.instance.hostname: service-registry
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/   
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /api/auth/**  
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://gest-contracts-finale:8070
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: CONTRACTS-SERVICE
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /api/nfts/**   
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://gest-nft:8081
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: NFT-SERVICE
      
               
  monsters-collection:
    image: "solidityapp"
    ports:
      - 8545:8545
    depends_on:
      - service-registry
    networks:
      - network-eureka  
    environment:  
      spring.data.mongodb.host : mongo
      eureka.instance.hostname: service-registry
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/ 
  nfts:
    image: "sf_nfts-microservice "
    ports:
      - 8081:8081
    depends_on:
      - service-registry
    networks:
      - network-eureka  
    environment:  
      spring.data.mongodb.host : mongo
      eureka.instance.hostname: service-registry
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/                       
  
  frontend:
    image: "nftmarketplace"
    ports:
      - 4200:80
    depends_on:
      - cloud-gatway
    networks:
      - network-eureka     
  mongodb:
    image: mongo:latest    
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - network-eureka    
  mongoSeed:
    image: mongo:latest
    networks:
      - network-eureka    
    links:
      - mongodb
   
         
      
networks:
 network-eureka: 